---
title: "Arizona State Realstate Property Analysis"
author: "Khairi Yi"
date: "Feb 1st, 2016"
output: html_document
---
1. Import dataset and cleaning
```{r}
datta_raw <- read.csv("/Users/blackboyyi/Opendoor/data_sci_snippet.csv", na.strings=c("","NA") )
datta <- datta_raw[,-11] #Leave the comment section for now
table(datta$ListingStatus); sum(is.na(datta$ClosePrice) == FALSE) #See the status of listings in the data. # There's discrepency of # Closed listing and # of listings that have ClosePrice, we will have a closer look below.
problem_data <- is.na(datta$ClosePrice) == FALSE & datta$ListingStatus != "Closed" ; dim(datta[problem_data,])[1] #There are 328 of problematic listing data.Such as an active listing has a closePrice.

#Final data set with Index of problemactic data removed. 
datta <- datta[!problem_data,]

#See all the variables status and levels of factors
names <- names(datta)
#Check the status of all variables, as well as different levels in different factors 
for (name in names){
  print(paste(name, class(datta[,name])))
}
sapply(datta[,-c(7,11)], levels)
# There are some extremelt low prices to be looked into
head(sort(datta$ClosePrice), 100)
# Remove 140 from the data. There are about 140 extremely low prices for non-mobile housing
unusual_price <- which(datta$ClosePrice <= 30000 & datta$DwellingType != "Mfg/Mobile Housing"); length(unusual_price)
datta <- datta[-unusual_price,]
# Restrict the listings in Arizon, so 11 of them are out of Arizona
datta  <- datta[which(datta$GeoLat > 31.35 & datta$GeoLat < 36.8 & datta$GeoLon > -114.7 & datta$GeoLon < -109), ]
# Lastly, I will remove "Mfg/Mobile housing" in the analysis, as the determined factors for this is very different from other normal houseing
datta <- datta[datta$DwellingType != "Mfg/Mobile Housing", ]
# Change NumBath bigger than 25 to 25's.
newbath <- as.factor(datta$NumBaths); newbath[newbath %in% c("0.07", "0.75", "1")] = "1"; newbath[newbath %in% c("1.25", "1.34", "1.5")] = "1.5"; newbath[newbath %in% c("1.57", "1.7", "1.72", "1.75","2", "2.1")] = "2"; 
newbath[newbath %in% c("2.25", "2.33", "2.34","2.5", "2.53")] = "2.5"; newbath[newbath %in% c("2.65", "2.67", "2.75", "3")] = 3; newbath[newbath %in% c("3.25", "3.4", "3.5")] = "3.5"; newbath[newbath %in% c("3.75", "4")] = "4"; newbath[newbath %in% c("4.25", "4.5", "4.75")] = "4.5"; newbath[newbath %in% c("5.5", "5.75", "6")] = "6"; newbath[newbath %in% c("6.5", "7", "7.5")] = 7; newbath[newbath %in% c("9.75", "10")] = 10; newbath[newbath %in% c("134", "175", "205", "212", "312", "1047")] = "25"
datta$NumBaths <- as.numeric(as.character(newbath))
```
2. Add new variables
```{r}
# duration: the length of time before a property is sold
# Transform date type variables into duration, duration: # of days
# Option: For listings that have not been closed. Choose closing date 2015 03 31, only for Active, Expired and Pending listings, as "cancelled", "temp off market" listings could have other reasons to exit the system.
CloseDate0 <- datta$CloseDate; CloseDate0[is.na(CloseDate0) & datta$ListingStatus %in% c("Active", "Expired", "Pending")] = "2015-03-31"
# Note: It's not used in this analysis due to uncertainties. 
datta$duration <- as.Date(CloseDate0, "%Y-%m-%d") - as.Date(datta$ListDate, "%Y-%m-%d")
# Facts:Longest closed deal took 385 days.
max(datta$duration[which(datta$ListingStatus == "Closed")])
datta$duration <- as.numeric(datta$duration, units = "days")
# price_diff: difference of ListPrice and ClosePrice
datta$price_diff <- datta$ListPrice - datta$ClosePrice 
#
geo <- data.frame(datta$GeoLat, datta$GeoLon, datta$ListingId); geo <- geo[complete.cases(geo),]; colnames(geo) <- c("Geolat", "GeoLon", "Neibough"); geo$Neibough = NULL

#########################
# Number of neighbourhood
clusters <- kmeans(geo, centers = 70, iter.max = 30);
#########################

datta0 <- datta[complete.cases(datta["GeoLat"]),] 
datta0$neighbour <- as.factor(clusters$cluster)
# Average price per square foot
datta0$price_per <- datta0$ClosePrice/datta0$LivingArea; sum(!is.na(datta0$price_per));sum(datta0$price_per > 200, na.rm = T)
#datta0 <- datta0[which(datta0$price_per <= 200), ]
# 3rd quarter of price_per = 140.8
expensive_house <- datta0[which(datta0$price_per > 150), ]
datta0[-which(datta0$price_per > 150 & datta0$LivingArea > 3000), ]
# See if it's really the causes of neighbourhood
by_neigh <- table(expensive_house$neighbour); by_neigh
by_area <- table(expensive_house$neighbour[which(expensive_house$LivingArea > 2000)]); by_area
#plot(by_neigh/by_area)
# As the ratio of the expensive, huge house is roughly the same , therefore the abnormality comes from the the sizes and prices of a house.
# Label the unusually expensive listings
type <- as.character(datta0$DwellingType)
type[c(which(datta0$price_per > 150 & datta0$LivingArea > 2000))] = "Unusual"
type[-c(which(datta0$price_per > 150 & datta0$LivingArea > 2000))] = "Normal"
datta0$others <- type
```

3. Check relationship of Duration and transaction price difference
```{r}
cor(datta$duration, datta$price_diff, use = "pairwise.complete.obs")
```
4. Stratify data and use which for cross-validation
```{r}
# See the correlations of numeric variables in the data set
attach(datta0); num_mat <- cbind(LivingArea, NumBedrooms, NumBaths, ExteriorStories, ListPrice,ClosePrice, duration, price_diff); cor(num_mat, use = "pairwise.complete.obs")

mod <- lm(ClosePrice ~ neighbour*LivingArea*NumBedrooms + DwellingType + 
                  NumBaths + Pool + ExteriorStories + type , data = datta0)
summary(mod)
plot(mod$fitted, mod$residuals); qqnorm(mod$fitted)
detach(datta0)
```

5. Check the distributions of ClosePrice & Simple models
```{r}
require(sampling)
trials <- matrix(nrow = 1000, ncol = 8, byrow = FALSE, dimnames = list(c(), c("nor_diff", "pred_diff", "short_t", "medium_t", "long_t", "Active", "Expired", "Pending")))
for (i in 1:2){
    set.seed(i)
    datta00 <- datta0[order(datta0$neighbour),]
    prop <- table(datta00$neighbour); prop_size <- round(prop*0.2); prop_size[prop_size == 0] = 1
    strat <- strata(datta00, stratanames = "neighbour", size = prop_size, method = "srswor")
    # Train and Test data set
    datta_test <- getdata(datta00,strat)[,-c(20,21,22)]
    datta_train <- getdata(datta00, datta00[-c(strat$ID_unit),])
    #Predictive model:
    mod <- lm(ClosePrice ~ neighbour*LivingArea*NumBedrooms*others + DwellingType  +
                        NumBaths + Pool + ExteriorStories, data = datta_train)

    results <- predict(mod, newdata = datta_test, interval = "prediction")
    difference <- abs(datta_test$ClosePrice - results[,1])
    difference_other <- results[,1] - datta_test$ListPrice
    
    #1.Normal average price difference between Listing and Closing
    nor_diff <- mean(abs(datta_train$ClosePrice - datta_train$ListPrice), na.rm = T)
    #2.Mean prediction difference: price differences in real closing price and the predicted price 
    pred_diff <- mean(difference, na.rm = T)
    #3.Separate listing sold within 71 days, versus 71 days to 365, versus longer than 365
    med <- median(datta_test$duration, na.rm = T)
    short_t <- mean(difference[which(datta_test$duration < med)], na.rm = T); medium_t <- mean(difference[which(datta_test$duration >= med & datta_test$duration < 365)], na.rm = T); long_t <- mean(difference[which(datta_test$duration >= 365)], na.rm = T)
    #Shows listing sold within median days returns less error
    unclosed <- tapply(difference_other[datta_test$ListingStatus %in% c("Active", "Pending", "Expired")], datta_test$ListingStatus[datta_test$ListingStatus %in% c("Active", "Pending", "Expired")], mean, na.rm = T)
    trials[i,] = c(nor_diff, pred_diff, short_t, medium_t, long_t, unclosed["Active"], unclosed["Expired"], unclosed["Pending"])
}
```
6. Exporting results
```{r}
write.csv(trials, "/Users/blackboyyi/Google Drive/Data Analysis/Prediction_normal_results.csv")
```

